name: run script

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: run_sh
        run: |
         chmod +x script.sh
         ./script.sh
         
      - name: Checkout
        uses: actions/checkout@v6.0.2